[package]
name = "finnel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.38"
derive_more = "0.99.17"
oxydized-money = "0.3.0"
semver = "1.0.23"
sqlite = "0.36.0"
thiserror = "1.0.61"

[dev-dependencies]
pretty_assertions = "1.4.0"
