# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "src/schema.rs"
patch_file = "src/schema.patch"
sqlite_integer_primary_key_is_bigint = true
custom_type_derives = ["diesel::query_builder::QueryId", "Clone"]
import_types = [
  "diesel::sql_types::*",
#  "diesel_full_text_search::types::*",
]

[migrations_directory]
dir = "migrations"
