[package]
name = "finnelctl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.86"
clap = "4.5.4"
clap-verbosity-flag = "2.2.0"
finnel = { path = "../finnel" }
toml = "0.8.14"
xdg = "2.5.2"

[dev-dependencies]
assert_fs = "1.1.1"
pretty_assertions = "1.4.0"
temp-env = "0.3.6"
